"""add_tables_routes

Revision ID: e0181b0902a9
Revises: 2a448066ead0
Create Date: 2026-04-10 06:58:59.116060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0181b0902a9'
down_revision: Union[str, Sequence[str], None] = '2a448066ead0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('shortDescription', sa.String(), nullable=False),
    sa.Column('fullDescription', sa.String(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('transport', sa.String(), nullable=False),
    sa.Column('budget', sa.Enum('ECONOMY', 'MEDIUM', 'OTHER', name='routebudgetenum'), nullable=False),
    sa.Column('volunteer', sa.Boolean(), nullable=False),
    sa.Column('volunteerImpact', sa.String(), nullable=False),
    sa.Column('petsAllowed', sa.Boolean(), nullable=False),
    sa.Column('kidsAllowed', sa.Boolean(), nullable=False),
    sa.Column('typeLabel', sa.String(), nullable=False),
    sa.Column('place', sa.String(), nullable=False),
    sa.Column('priceFrom', sa.Float(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('coordinates_latitude', sa.Float(), nullable=False),
    sa.Column('coordinates_longitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('route_company',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('route_gallery',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('route_interests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('interest_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('route_tips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('tip', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('full_name', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'full_name')
    op.drop_table('route_tips')
    op.drop_table('route_interests')
    op.drop_table('route_gallery')
    op.drop_table('route_company')
    op.drop_table('routes')
    op.drop_table('interests')
    op.drop_table('companies')
    # ### end Alembic commands ###
