export const mockBookings = [
    {
        id: 1001,
        status: "pending",
        createdAt: "18.06.2026, 11:42",
        route: {
            id: 1,
            title: "Волонтёрский выезд «Лес и берег»",
            place: "Воткинский район",
            duration: "3",
            date: "19–21 июля",
            priceFrom: "от 2 900 ₽",
        },
        user: {
            fullName: "Мария Соколова",
            username: "maria.s",
            email: "maria@example.com",
            phone: "+7 (912) 111-22-33",
        },
        people: "2",
        comment: "Интересует участие именно в волонтёрской программе, приедем вдвоём.",
    },
    {
        id: 1002,
        status: "approved",
        createdAt: "17.06.2026, 18:05",
        route: {
            id: 2,
            title: "Эко-маршрут «Чепца и сосновый бор»",
            place: "Глазовский район",
            duration: "2",
            date: "20–21 июля",
            priceFrom: "от 3 900 ₽",
        },
        user: {
            fullName: "Игорь Петров",
            username: "igpetrov",
            email: "igor@example.com",
            phone: "+7 (999) 555-44-33",
        },
        people: "1",
        comment: "Нужен ранний выезд, буду один.",
    },
    {
        id: 1003,
        status: "cancelled",
        createdAt: "16.06.2026, 09:14",
        route: {
            id: 3,
            title: "Исторический маршрут «Старая Ижевская слобода»",
            place: "Ижевск",
            duration: "1",
            date: "22 июля",
            priceFrom: "от 1 900 ₽",
        },
        user: {
            fullName: "Анна Кузнецова",
            username: "anna_k",
            email: "anna@example.com",
            phone: "+7 (950) 777-12-12",
        },
        people: "3",
        comment: "Планировали семейную поездку, но даты уже не подходят.",
    },
];