export const routesData = [
    {
        id: 1,
        title: "Волонтёрский выезд «Лес и берег»",
        shortDescription:
            "Трёхдневная социально значимая поездка с уборкой береговой линии и восстановлением экотропы.",
        fullDescription:
            "Маршрут объединяет отдых на природе и реальную помощь территории: участники помогают очистить берег, укрепить туристическую тропу и участвуют в экологическом просвещении для местных жителей. Поездка подойдёт тем, кто хочет совместить впечатления, активность и вклад в сохранение природной среды.",
        duration: "3",
        company: ["friends", "solo"],
        transport: "car",
        budget: "econom",
        interests: ["nature", "active", "volunteer"],
        volunteer: true,
        volunteerImpact:
            "Уборка береговой линии, сортировка отходов, помощь в благоустройстве тропы и работа вместе с локальным эко-сообществом.",
        petsAllowed: false,
        kidsAllowed: false,
        typeLabel: "Автомобильный",
        place: "Воткинский район",
        rating: 4.9,
        reviewsCount: 184,
        priceFrom: "от 2 900 ₽",
        bookingDates: ["12–14 июля", "19–21 июля", "26–28 июля"],
        image:
            "https://images.unsplash.com/photo-1522163182402-834f871fd851?q=80&w=1600&auto=format&fit=crop",
        gallery: [
            "https://images.unsplash.com/photo-1501554728187-ce583db33af7?q=80&w=1200&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1521295121783-8a321d551ad2?q=80&w=1200&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1527631746610-bca00a040d60?q=80&w=1200&auto=format&fit=crop",
        ],
        tips: ["Спальник и фонарь", "Перчатки и ветровка", "Подготовьте аптечку"],
        coordinates: { lat: 57.0486, lng: 53.9872 },
        comments: [
            {
                id: 1,
                author: "Екатерина",
                date: "14.04.2026",
                rating: 5,
                text: "Очень сильное впечатление: не просто поездка, а реально полезное дело.",
            },
            {
                id: 2,
                author: "Роман",
                date: "03.05.2026",
                rating: 5,
                text: "Хорошая организация, комфортный темп и классная команда.",
            },
            {
                id: 3,
                author: "Лиза",
                date: "19.05.2026",
                rating: 4,
                text: "Советую брать тёплую одежду на вечер. Формат понравился.",
            },
        ],
    },
    {
        id: 2,
        title: "Эко-маршрут «Чепца и сосновый бор»",
        shortDescription:
            "Двухдневная поездка по природным локациям с лёгким волонтёрским блоком.",
        fullDescription:
            "Маршрут сочетает прогулки по сосновому бору, обзорные точки у реки Чепцы и участие в локальной экологической акции.",
        duration: "2",
        company: ["friends", "solo"],
        transport: "car",
        budget: "medium",
        interests: ["nature", "active", "volunteer"],
        volunteer: true,
        volunteerImpact:
            "Участники присоединяются к очистке тропы, установке навигационных меток и мини-акции по восстановлению мест отдыха.",
        petsAllowed: false,
        kidsAllowed: true,
        typeLabel: "Автомобильный",
        place: "Глазовский район",
        rating: 4.8,
        reviewsCount: 128,
        priceFrom: "от 3 900 ₽",
        bookingDates: ["13–14 июля", "20–21 июля", "27–28 июля"],
        image:
            "https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=80&w=1600&auto=format&fit=crop",
        gallery: [
            "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?q=80&w=1200&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?q=80&w=1200&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1501785888041-af3ef285b470?q=80&w=1200&auto=format&fit=crop",
        ],
        tips: ["Удобная обувь", "Перчатки для эко-акции", "Вода и дождевик"],
        coordinates: { lat: 58.1394, lng: 52.6747 },
        comments: [
            {
                id: 1,
                author: "Анна",
                date: "12.03.2026",
                rating: 5,
                text: "Очень красивый маршрут, особенно утром.",
            },
            {
                id: 2,
                author: "Игорь",
                date: "18.03.2026",
                rating: 4,
                text: "Для выходных подходит отлично.",
            },
            {
                id: 3,
                author: "Марина",
                date: "01.04.2026",
                rating: 5,
                text: "Понравилась идея объединить прогулку и помощь природе.",
            },
        ],
    },
    {
        id: 3,
        title: "Исторический маршрут «Старая Ижевская слобода»",
        shortDescription:
            "Однодневный маршрут по историческим и культурным точкам Ижевска.",
        fullDescription:
            "Маршрут проходит через музейные и архитектурные локации, набережную и исторический центр.",
        duration: "1",
        company: ["solo", "family", "friends"],
        transport: "bus",
        budget: "econom",
        interests: ["history", "culture", "gastronomy"],
        volunteer: false,
        volunteerImpact: "",
        petsAllowed: true,
        kidsAllowed: true,
        typeLabel: "Автобусный",
        place: "Ижевск",
        rating: 4.6,
        reviewsCount: 91,
        priceFrom: "от 1 900 ₽",
        bookingDates: ["15 июля", "22 июля", "29 июля"],
        image:
            "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?q=80&w=1600&auto=format&fit=crop",
        gallery: [
            "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?q=80&w=1200&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?q=80&w=1200&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1518005020951-eccb494ad742?q=80&w=1200&auto=format&fit=crop",
        ],
        tips: ["Возьмите пауэрбанк", "Уточните часы музеев", "Подойдёт для детей"],
        coordinates: { lat: 56.8526, lng: 53.2045 },
        comments: [
            { id: 1, author: "Ольга", date: "08.02.2026", rating: 5, text: "Хороший вариант для первого знакомства с городом." },
            { id: 2, author: "Денис", date: "15.02.2026", rating: 4, text: "Маршрут спокойный, без перегруза." },
            { id: 3, author: "Светлана", date: "29.03.2026", rating: 4, text: "С детьми было комфортно." },
        ],
    },
    {
        id: 4,
        title: "Пеший маршрут «Тропа легенд»",
        shortDescription:
            "Активный однодневный маршрут с природными и этнокультурными точками.",
        fullDescription:
            "Пеший формат для любителей активного отдыха. Маршрут сочетает природные виды и атмосферные остановки.",
        duration: "1",
        company: ["solo", "friends"],
        transport: "walking",
        budget: "econom",
        interests: ["nature", "active", "history"],
        volunteer: false,
        volunteerImpact: "",
        petsAllowed: true,
        kidsAllowed: false,
        typeLabel: "Пеший",
        place: "Шарканский район",
        rating: 4.7,
        reviewsCount: 73,
        priceFrom: "от 2 100 ₽",
        bookingDates: ["11 июля", "18 июля", "25 июля"],
        image:
            "https://images.unsplash.com/photo-1551632811-561732d1e306?q=80&w=1600&auto=format&fit=crop",
        gallery: [
            "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=1200&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1500534623283-312aade485b7?q=80&w=1200&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1465310477141-6fb93167a273?q=80&w=1200&auto=format&fit=crop",
        ],
        tips: ["Треккинговая обувь", "Небольшой рюкзак", "Подойдёт для одного"],
        coordinates: { lat: 57.3064, lng: 52.2451 },
        comments: [
            { id: 1, author: "Михаил", date: "07.02.2026", rating: 5, text: "Хороший маршрут для одного дня." },
            { id: 2, author: "Полина", date: "19.02.2026", rating: 4, text: "Маршрут бодрый, но без перегруза." },
            { id: 3, author: "Егор", date: "30.03.2026", rating: 5, text: "Для компании друзей зашёл отлично." },
        ],
    },
];

export const interestOptions = [
    { value: "history", label: "История" },
    { value: "culture", label: "Культура" },
    { value: "nature", label: "Природа" },
    { value: "active", label: "Активный отдых" },
    { value: "gastronomy", label: "Гастрономия" },
    { value: "volunteer", label: "Волонтёрство" },
];